# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardnews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tendency', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=30)),
                ('target', models.CharField(max_length=30)),
                ('article', models.TextField()),
                ('articleUrl', models.CharField(max_length=50)),
                ('publish_time', models.DateField()),
                ('collecting_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
