# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardnews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardnews',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
