# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardnews', '0002_auto_20170509_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardnews',
            name='articleUrl',
            field=models.URLField(),
        ),
    ]
