# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardnews', '0003_auto_20170509_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardnews',
            name='publish_time',
            field=models.CharField(max_length=50),
        ),
    ]
