# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-11 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardnews', '0005_auto_20170509_0304'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('article', models.TextField()),
                ('img', models.ImageField(upload_to='uploads/%Y/%m/%d/orig')),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cardnews',
        ),
    ]
