# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-12 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardnews', '0006_auto_20170811_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='cardNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('article', models.TextField()),
                ('imgUrl', models.CharField(max_length=40)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
