# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-16 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardnews', '0008_auto_20170812_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardnews',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
